Repository perftool-incubator/rickshaw, pull requests merged in 2021-12, with the labels that each got.

#228 properly convert client/server lists
  endpoints/base
Labels: bug

#229 Incremental search/build/push for images
  rickshaw-run
Labels: enhancement

#232 update multi-stage container build output
  rickshaw-run
Labels: bug, enhancement
