Repository perftool-incubator/rickshaw, pull requests merged in 2024-07, with the labels that each got.

#508 Dev kmr
  rickshaw-run
  rickshaw-settings.json
Labels: enhancement

#509 Dev kmr
  .github/workflows/crucible-ci.yaml
  .github/workflows/crucible-merged.yaml
  .github/workflows/faux-crucible-ci.yaml
Labels: enhancement

#510 Dev kmr2
  endpoints/endpoints.py
  endpoints/remotehosts/remotehosts.py
  rickshaw-run
Labels: enhancement

#512 Dev kmr2
  endpoints/endpoints.py
  endpoints/remotehosts/remotehosts.py
Labels: bug

#525 New userenv for rhel-ai
  userenvs/rhel-ai.json
  userenvs/rhel-ai/requirements/02-python.json
  userenvs/rhel-ai/requirements/03-core-utils.json
  userenvs/rhel-ai/requirements/04-core-perl.json
  userenvs/rhel-ai/requirements/05-core-node.json
  userenvs/rhel-ai/schema.json
  userenvs/rhel-ai/userenv.json
Labels: rhel-ai

#526 Dev kmr2
  .github/workflows/crucible-ci.yaml
  .github/workflows/crucible-merged.yaml
  .github/workflows/faux-crucible-ci.yaml
  .github/workflows/faux-unittest.yaml
  .github/workflows/run-crucible-tracking.yaml
  .github/workflows/unittest.yaml
Labels: enhancement

#527 prevent an invalid state from crashing the remotehosts.py remote_imag…
  endpoints/remotehosts/remotehosts.py
Labels: bug

#529 add expiration timestamp refresh retries
  rickshaw-run
Labels: bug, enhancement
